# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: google-auth
# app and org for use with dashboard.serverless.com
app: google-auth
org: amio2sxjp

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

plugins:
  - serverless-offline

# custom:
#   serverless-offline:
#     httpsProtocol: "cert"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

  vpc:
    securityGroupIds:
      - ${param:VPC_SG}
    subnetIds:
      - ${param:VPC_SUBNET_1}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"

  # you can define service wide environment variables here
  environment:
    STORE_DB_NAME: ${param:STORE_DB_NAME}
    STORE_DB_PASSWORD: ${param:STORE_DB_PASSWORD}
    STORE_DB_HOST: ${param:STORE_DB_HOST}
    STORE_DB_PORT: ${param:STORE_DB_PORT}
    STORE_DB_USER: ${param:STORE_DB_USER}

    ROOT_URL: ${param:ROOT_URL}
    GOOGLE_CLIENT_ID: ${param:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${param:GOOGLE_CLIENT_SECRET}

    STAGE: ${self:provider.stage}
    JWT_SECRET: ${param:JWT_SECRET}

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"



# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  googleAuthUrl:
    handler: Handlers/Google.googleAuthUrl
    events:
      - http:
          path: auth/google/authUrl
          method: get
  googleAuthCallback:
    handler: Handlers/Google.googleAuthCallback
    events:
      - http:
          path: auth/google/callback
          method: get
  googleAuthCallbackTest:
    handler: Handlers/Google.googleAuthCallbackTest
    events:
      - http:
          path: auth/google/callback-test
          method: get
